version: "3.8"

services:
  fastapi:
    container_name: fastapi
    build: ./server/
    restart: always
  
  nginx:
    depends_on:
      - fastapi
    container_name: nginx
    build: ./client
    ports:
      - "80:80"
    restart: always