version: "3.8"

services:
  fastapi:
    container_name: fastapi
    image: "coco-fastapi:0.0.1"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./server/app/.env
  
  nginx:
    depends_on:
      - fastapi
    container_name: nginx
    image: "coco-nginx:0.0.1"
    ports:
      - "80:80"
    restart: always
    env_file:
      - ./client/.env