"""add is_public column in post table

Revision ID: 08f50ddb5e8e
Revises: 9411b75ef183
Create Date: 2022-04-16 16:14:17.719061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f50ddb5e8e'
down_revision = '9411b75ef183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.execute("UPDATE posts SET is_public = IF(ISNULL(is_public), 1, is_public)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_public')
    # ### end Alembic commands ###
