"""add bucketlist.detail, users.image_path column and change string type to text type in comment.content

Revision ID: 277a255d338d
Revises: 08f50ddb5e8e
Create Date: 2022-04-16 20:07:49.207011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '277a255d338d'
down_revision = '08f50ddb5e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist', sa.Column('detail', sa.TEXT(), nullable=True))
    op.drop_column('bucketlist', 'date')
    op.alter_column('comments', 'content',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('users', sa.Column('image_path', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_path')
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
    op.add_column('bucketlist', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('bucketlist', 'detail')
    # ### end Alembic commands ###
