"""create bucketlist table

Revision ID: 5c338b3ace81
Revises: 6235118a9680
Create Date: 2022-03-28 22:35:33.269330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c338b3ace81'
down_revision = '6235118a9680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bucketlist_id'), 'bucketlist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bucketlist_id'), table_name='bucketlist')
    op.drop_table('bucketlist')
    # ### end Alembic commands ###
