"""add foreignkey constraint

Revision ID: 9411b75ef183
Revises: 27be944525a7
Create Date: 2022-03-29 19:03:05.742571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9411b75ef183'
down_revision = '27be944525a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bookmarks', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'bookmarks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    # ### end Alembic commands ###
