"""change users.domain max_length

Revision ID: 96b35c9e8bc5
Revises: 5c338b3ace81
Create Date: 2022-03-28 22:51:31.574218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96b35c9e8bc5'
down_revision = '5c338b3ace81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'domain',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'domain',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
